// <auto-generated />
using System;
using Application_Camion_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application_Camion_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708072859_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application_Camion_API.Models.Etape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Garage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<int>("TourneeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TourneeId");

                    b.ToTable("Etapes");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Tournee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeUnique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreateurId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Terminee")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.ToTable("Tournees");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EtapeId")
                        .HasColumnType("integer");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Recupere")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EtapeId");

                    b.ToTable("Vehicules");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Etape", b =>
                {
                    b.HasOne("Application_Camion_API.Models.Tournee", "Tournee")
                        .WithMany("Etapes")
                        .HasForeignKey("TourneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournee");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Tournee", b =>
                {
                    b.HasOne("Application_Camion_API.Models.Utilisateur", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Vehicule", b =>
                {
                    b.HasOne("Application_Camion_API.Models.Etape", "Etape")
                        .WithMany("Vehicules")
                        .HasForeignKey("EtapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etape");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Etape", b =>
                {
                    b.Navigation("Vehicules");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Tournee", b =>
                {
                    b.Navigation("Etapes");
                });
#pragma warning restore 612, 618
        }
    }
}
