// <auto-generated />
using System;
using Application_Camion_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application_Camion_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708105213_AddVehicleCatalogAndCarrierCapacity")]
    partial class AddVehicleCatalogAndCarrierCapacity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application_Camion_API.Models.CamionPorteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<int>("ChargeUtileKg")
                        .HasColumnType("integer");

                    b.Property<int>("HauteurMaxCm")
                        .HasColumnType("integer");

                    b.Property<int>("LargeurUtileCm")
                        .HasColumnType("integer");

                    b.Property<int>("LongueurUtileCm")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NombreNiveaux")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CamionsPorteurs");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Etape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Garage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<int>("TourneeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TourneeId");

                    b.ToTable("Etapes");
                });

            modelBuilder.Entity("Application_Camion_API.Models.ModeleVehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HauteurCm")
                        .HasColumnType("integer");

                    b.Property<int>("LargeurCm")
                        .HasColumnType("integer");

                    b.Property<int>("LongueurCm")
                        .HasColumnType("integer");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PoidsKg")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Marque", "Modele")
                        .IsUnique();

                    b.ToTable("ModelesVehicules");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Tournee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CamionPorteurId")
                        .HasColumnType("integer");

                    b.Property<string>("CodeUnique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Terminee")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CamionPorteurId");

                    b.HasIndex("CodeUnique")
                        .IsUnique();

                    b.ToTable("Tournees");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseLivraison")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientLivraison")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EtapeId")
                        .HasColumnType("integer");

                    b.Property<int>("HauteurCm")
                        .HasColumnType("integer");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LargeurCm")
                        .HasColumnType("integer");

                    b.Property<int>("LongueurCm")
                        .HasColumnType("integer");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModeleVehiculeId")
                        .HasColumnType("integer");

                    b.Property<int>("PoidsKg")
                        .HasColumnType("integer");

                    b.Property<bool>("Recupere")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EtapeId");

                    b.HasIndex("ModeleVehiculeId");

                    b.ToTable("Vehicules");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Etape", b =>
                {
                    b.HasOne("Application_Camion_API.Models.Tournee", "Tournee")
                        .WithMany("Etapes")
                        .HasForeignKey("TourneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournee");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Tournee", b =>
                {
                    b.HasOne("Application_Camion_API.Models.CamionPorteur", "CamionPorteur")
                        .WithMany("Tournees")
                        .HasForeignKey("CamionPorteurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CamionPorteur");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Vehicule", b =>
                {
                    b.HasOne("Application_Camion_API.Models.Etape", "Etape")
                        .WithMany("Vehicules")
                        .HasForeignKey("EtapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application_Camion_API.Models.ModeleVehicule", "ModeleVehicule")
                        .WithMany("Vehicules")
                        .HasForeignKey("ModeleVehiculeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Etape");

                    b.Navigation("ModeleVehicule");
                });

            modelBuilder.Entity("Application_Camion_API.Models.CamionPorteur", b =>
                {
                    b.Navigation("Tournees");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Etape", b =>
                {
                    b.Navigation("Vehicules");
                });

            modelBuilder.Entity("Application_Camion_API.Models.ModeleVehicule", b =>
                {
                    b.Navigation("Vehicules");
                });

            modelBuilder.Entity("Application_Camion_API.Models.Tournee", b =>
                {
                    b.Navigation("Etapes");
                });
#pragma warning restore 612, 618
        }
    }
}
